import { Poppins } from "next/font/google";
import "./globals.css";
import FloatingShape from "@/components/FloatingShape/FloatingShape";
import { ClerkProvider } from "@clerk/nextjs";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700"],
});

export const metadata = {
  title: "DROP IT - YOUR PERSONAL FILE SHARING PLATFORM",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${poppins.className} bg-[#e0e0e2]`}>{children}</body>
      </html>
    </ClerkProvider>
  );
}
